server:
  port: 8089
link:
  verify-email: https://love-haven.vercel.app/verify-result
cors:
  allowed-origins: "http://34.126.134.243:8888"
spring:
  application:
    name: account-service
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: "34.126.134.243:9092"
      bindings:
        # consume OrderCreatedEvent (function bean name: orderCreatedConsumer -> binding: orderCreatedConsumer-in-0)
        orderCreatedConsumer-in-0:
          destination: order-created
          contentType: application/json
          group: payment-service-group
        # publish payment results
        paymentSucceeded-out-0:
          destination: payment-succeeded
        paymentFailed-out-0:
          destination: payment-failed
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000
    url: jdbc:postgresql://34.126.134.243:6432/usersdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.126.134.243:8090/realms/sketchnote
  cache:
    type: redis


  data:
    redis:
      host: 34.126.134.243
      port: 6379

#  kafka:
#    properties:
#      enable.idempotence: true
#      max.in.flight.requests.per.connection: 5
#    bootstrap-servers: 139.59.119.65:9092   # địa chỉ Kafka KRaft broker
#    consumer:
#      group-id: identity-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all
#      retries: 1
#    listener:
#      ack-mode: record
idp:
  url: http://34.126.134.243:8090
  client-id: sketchnote
  client-secret: QYHYNsUNOS40S0Z28N7IytIf9bLYhtK3

eureka:
  client:
    service-url:
      defaultZone: http://34.126.134.243:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 34.126.98.83

