server:
  port: 8089
cors:
  allowed-origins: "http://139.59.119.65:8888"
app:
  ip: 139.59.119.65

spring:
  application:
    name: account-service
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:139.59.119.65:9092}
      bindings:
        # consume OrderCreatedEvent (function bean name: orderCreatedConsumer -> binding: orderCreatedConsumer-in-0)
        orderCreatedConsumer-in-0:
          destination: order-created
          contentType: application/json
          group: payment-service-group
        # publish payment results
        paymentSucceeded-out-0:
          destination: payment-succeeded
        paymentFailed-out-0:
          destination: payment-failed
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000
    url: jdbc:postgresql://139.59.119.65:6432/usersdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://139.59.119.65:8090/realms/sketchnote
  cache:
    type: redis

  data:
    redis:
      host: 139.59.119.65
      port: 6379

idp:
  url: http://139.59.119.65:8090
  client-id: sketchnote
  client-secret: QYHYNsUNOS40S0Z28N7IytIf9bLYhtK3

payos:
  client-id: 1d3270ba-354d-4ac1-9693-09bd3ef01a47
  api-key: 8be8c8ef-3f5f-4fd8-ae46-4a170ca132e5
  checksum-key: f9386305d4e364c17bbe31b5beffeb99def6fa6da7ea63afc856301a8edbf851

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/