server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: learning-service
              uri: lb://learning-service
              predicates:
                - Path=/api/learning/**

            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/users/**, /api/auth/**, /api/roles/**,/api/blogs/**,/api/payment/**,/api/contents/**, /api/wallet/**, /api/subscription-plans/**, /api/payments/**, /api/feedback/**, /api/notifications/**, /api/messages/**, /api/credits/**, /api/credit-packages/**, /api/admin/**, /api/withdraw/**, /api/admin/withdraw/**,/api/bank-accounts/**,/api/internal/**

            - id: project-service
              uri: lb://project-service
              predicates:
                - Path=/api/projects/**, /api/pages/**,/api/collaborations/**,/api/images/**,/api/category-papers/**, /api/paper-templates/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**


springdoc:
  swagger-ui:
    urls:
      - name: learning-service
        url: /learning-service/v3/api-docs
      - name: account-service
        url: /account-service/v3/api-docs
      - name: project-service
        url: /project-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://34.177.90.19:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 34.177.90.19
