server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: learning-service
              uri: lb://learning-service
              predicates:
                - Path=/api/learning/**
            - id: identity-service
              uri: lb://account-service
              predicates:
                - Path=/api/users/**, /api/auth/**, /api/roles/**,/api/blogs/**,/api/payment/**,/api/wallet/**
            - id: project-service
              uri: lb://project-service
              predicates:
                - Path=/api/projects/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

            - id: project-ws
              uri: lb:ws://project-service
              predicates:
                - Path=/ws/**
                -
            - id: interaction-service
              uri: lb://interaction-service
              predicates:
                - Path=/api/interactions/**



springdoc:
  swagger-ui:
    urls:
      - name: learning-service
        url: /learning-service/v3/api-docs
      - name: account-service
        url: /account-service/v3/api-docs
      - name: project-service
        url: /project-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: interaction-service
        url: /interaction-service/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
#  instance:
#    prefer-ip-address: true
#    ip-address: localhost
