server:
  port: 8087

# Gateway configuration for Swagger (LOCAL)
gateway:
  url: http://localhost:8888  # Local gateway
  project-path: ""  # Không có prefix, routes trực tiếp /api/projects/**, /api/pages/**...
ai:
  url: http://34.126.98.83:8000

spring:
  application:
    name: project-service
  cloud:
    discovery:
      enabled: true

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000
    url: jdbc:postgresql://34.177.90.19:6432/projectdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.177.90.19:8090/realms/sketchnote

  cache:
    type: redis

  data:
    redis:
      host: 34.177.90.19
      port: 6379
      password: TaiDepTrai_VoDich_2025!@#
      # password: your_password (nếu có bật password)
  gemini:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    location: us-central1
    model: imagen-3.0-generate-002
    num-images: 2
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      bucket-name: ${AWS_BUCKET_NAME}
      region: ap-southeast-1
      presign-expiration: 10 # phút

  kafka:
    properties:
      enable.idempotence: true
      max.in.flight.requests.per.connection: 5
      bootstrap-servers: 34.177.90.19:9092
    consumer:
      group-id: project-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 1
    listener:
      ack-mode: record


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    com.sketchnotes.project_service: DEBUG
